# Generated by Django 4.2.15 on 2024-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_process', 'В обработке'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
